"""
============================================================
RecruitOS

Module      : Enterprise Resume Parser
Sprint      : 5.6.0
Version     : 3.0.0
Author      : Tamilvanan A

Purpose:
Transforms a processed resume document into the RecruitOS
Candidate domain model.

Master-data integration:

    PersonalExtractor
    SkillExtractor
    EducationExtractor
    CertificationExtractor

All master-data driven extraction uses:

    RecruitOS_Configuration.xlsx

No skill, education, or certification master values are
hardcoded inside ResumeParser.

============================================================
"""

from __future__ import annotations

import re
from typing import Any, Dict, List

from models.candidate import Candidate

from parser.extractors.personal_extractor import (
    PersonalExtractor
)

from parser.extractors.skill_extractor import (
    SkillExtractor
)

from parser.extractors.education_extractor import (
    EducationExtractor
)

from parser.extractors.certification_extractor import (
    CertificationExtractor
)


class ResumeParser:
    """
    Enterprise Resume Parser.

    Input:

        Processed document dictionary generated by
        DocumentManager / ExtractionService.

    Output:

        Candidate domain object.
    """

    EXPERIENCE_PATTERN = re.compile(
        r"(?<!\d)"
        r"(\d+(?:\.\d+)?)"
        r"\s*"
        r"(?:\+)?"
        r"\s*"
        r"(?:years?|yrs?)"
        r"(?!\w)",
        re.IGNORECASE
    )

    # ========================================================
    # Duplicate Removal
    # ========================================================

    @staticmethod
    def remove_duplicates(
        values: List[str]
    ) -> List[str]:
        """
        Remove duplicate string values case-insensitively
        while preserving original order.
        """

        if not values:

            return []

        unique = []

        seen = set()

        for value in values:

            if value is None:

                continue

            cleaned = str(
                value
            ).strip()

            if not cleaned:

                continue

            normalized = (
                cleaned.lower()
            )

            if normalized in seen:

                continue

            seen.add(
                normalized
            )

            unique.append(
                cleaned
            )

        return unique

    # ========================================================
    # Experience Extraction
    # ========================================================

    @classmethod
    def extract_experience(
        cls,
        text: str
    ) -> float:
        """
        Extract likely total years of experience.

        Current deterministic strategy:

            - Find explicit "<number> years/yrs" expressions.
            - Return the highest detected value.

        Example:

            "5 years experience"
                -> 5.0

        More advanced employment timeline calculation belongs
        to a future experience extraction milestone.
        """

        if not text:

            return 0.0

        matches = (
            cls.EXPERIENCE_PATTERN.findall(
                text
            )
        )

        if not matches:

            return 0.0

        values = []

        for match in matches:

            try:

                values.append(
                    float(
                        match
                    )
                )

            except (
                TypeError,
                ValueError
            ):

                continue

        if not values:

            return 0.0

        return max(
            values
        )

    # ========================================================
    # Skill Extraction
    # ========================================================

    @classmethod
    def extract_skills(
        cls,
        text: str
    ) -> List[str]:
        """
        Extract standardized skills using SkillExtractor.
        """

        if not text:

            return []

        skills = (
            SkillExtractor.extract(
                text
            )
        )

        return cls.remove_duplicates(
            skills
        )

    # ========================================================
    # Education Extraction
    # ========================================================

    @classmethod
    def extract_education(
        cls,
        text: str
    ) -> List[str]:
        """
        Extract standardized education using the configured
        Education repository.
        """

        if not text:

            return []

        education = (
            EducationExtractor.extract(
                text
            )
        )

        return cls.remove_duplicates(
            education
        )

    # ========================================================
    # Certification Extraction
    # ========================================================

    @classmethod
    def extract_certifications(
        cls,
        text: str
    ) -> List[str]:
        """
        Extract standardized certifications using the
        configured Certification repository.
        """

        if not text:

            return []

        certifications = (
            CertificationExtractor.extract(
                text
            )
        )

        return cls.remove_duplicates(
            certifications
        )

    # ========================================================
    # Tools Extraction
    # ========================================================

    @staticmethod
    def extract_tools(
        text: str
    ) -> List[str]:
        """
        Tool-specific extraction is intentionally deferred.

        Skills configured as tools can currently be managed
        through the Skills master until the dedicated Tools
        taxonomy is introduced.
        """

        return []

    # ========================================================
    # Project Extraction
    # ========================================================

    @staticmethod
    def extract_projects(
        text: str
    ) -> List[str]:
        """
        Structured project extraction is scheduled for a
        later parser milestone.
        """

        return []

    # ========================================================
    # Companies Extraction
    # ========================================================

    @staticmethod
    def extract_companies(
        text: str
    ) -> List[str]:
        """
        Structured company extraction is scheduled for a
        later parser milestone.
        """

        return []

    # ========================================================
    # Soft Skills
    # ========================================================

    @staticmethod
    def extract_soft_skills(
        text: str
    ) -> List[str]:
        """
        Soft-skill extraction will use its own configuration
        and NLP rules in a future milestone.

        Nothing is hardcoded here.
        """

        return []

    # ========================================================
    # Parse Resume
    # ========================================================

    @classmethod
    def parse(
        cls,
        document: Dict[str, Any]
    ) -> Candidate:
        """
        Convert a processed resume document into Candidate.

        Expected document structure:

        {
            "text": "...",
            "file_name": "...",
            "file_type": "...",
            "file_path": "...",
            "sections": {...},
            "metadata": {...}
        }
        """

        candidate = Candidate()

        if not document:

            return candidate

        source_file = str(
            document.get(
                "file_name",
                ""
            )
            or ""
        ).strip()

        candidate.source_file = (
            source_file
        )

        text = str(
            document.get(
                "text",
                ""
            )
            or ""
        ).strip()

        candidate.raw_text = text

        if not text:

            return candidate

        # ====================================================
        # Personal Information
        # ====================================================

        personal = (
            PersonalExtractor.extract(
                text
            )
            or {}
        )

        candidate.full_name = str(
            personal.get(
                "name",
                ""
            )
            or ""
        ).strip()

        candidate.email = str(
            personal.get(
                "email",
                ""
            )
            or ""
        ).strip()

        candidate.phone = str(
            personal.get(
                "phone",
                ""
            )
            or ""
        ).strip()

        candidate.location = str(
            personal.get(
                "location",
                ""
            )
            or ""
        ).strip()

        # ====================================================
        # Experience
        # ====================================================

        candidate.total_experience = (
            cls.extract_experience(
                text
            )
        )

        # ====================================================
        # Education
        # ====================================================

        candidate.education = (
            cls.extract_education(
                text
            )
        )

        # ====================================================
        # Certifications
        # ====================================================

        candidate.certifications = (
            cls.extract_certifications(
                text
            )
        )

        # ====================================================
        # Technical Skills
        # ====================================================

        candidate.technical_skills = (
            cls.extract_skills(
                text
            )
        )

        # ====================================================
        # Future Structured Extraction Areas
        # ====================================================

        candidate.soft_skills = (
            cls.extract_soft_skills(
                text
            )
        )

        candidate.tools = (
            cls.extract_tools(
                text
            )
        )

        candidate.projects = (
            cls.extract_projects(
                text
            )
        )

        candidate.companies = (
            cls.extract_companies(
                text
            )
        )

        return candidate